trigger:
  branches:
    include:
      - main

pool:
  name: Internal

steps:
  - bash: |
      cp $(Build.SourcesDirectory)/signature-generator.html /var/www/fpt/app/public/signature-generator.html
    displayName: 'Deploy signature-generator.html to FPT-dev-01'